version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres
    environment:
      POSTGRES_DB: rag_system_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: api
    command: sh -c "python3 ingest.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: rag_system_local
      DB_USER: postgres
      DB_PASSWORD: postgres
      EMBED_MODEL_PATH: /app/models/multilingual-e5-base
      LLM_MODEL_PATH: /app/models/Mistral-7B-Instruct-v0.3.Q8_0.gguf
      N_GPU_LAYERS: 35
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models:ro
      - ../data:/app/data:ro
    networks:
      - rag_net
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      API_URL: http://api:8000
    ports:
      - "8501:8501"
    networks:
      - rag_net
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  rag_net:
    driver: bridge